#!/bin/bash -ue

. /usr/share/cassandra/cassandra.in.sh

exec -a nodetool /usr/bin/java -javaagent:${CASSANDRA_HOME}/agents/jamm-0.3.0.jar -Dcassandra.storagedir=/var/lib/cassandra/ -Dcassandra.config=file://${CASSANDRA_HOME}/cassandra.yaml  -cp "${CASSANDRA_CLASSPATH}" org.apache.cassandra.tools.NodeTool $@